export const cardDataA = [
  {
    title: "A1",
    segments: ["A", "B", "C"],
    qualifications: ["BSc", "MSc", "Diploma"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "42%",
    applied: "65%",
    calledBack: 123,
  },
  {
    title: "A2",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "A3",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],

    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "A4",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "A5",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "A6",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "A7",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
];

export const cardDataB = [
  {
    title: "B1",
    segments: ["A", "B", "C"],
    qualifications: ["BSc", "MSc", "Diploma"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "42%",
    applied: "65%",
    calledBack: 123,
  },
  {
    title: "B2",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "B3",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "B4",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "B5",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "B6",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "B7",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
];

export const cardDataC = [
  {
    title: "C1",
    segments: ["A", "B", "C"],
    qualifications: ["BSc", "MSc", "Diploma"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "42%",
    applied: "65%",
    calledBack: 123,
  },
  {
    title: "C2",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "C3",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],

    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "C4",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "C5",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "C6",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "C7",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
];

export const cardDataD = [
  {
    title: "D1",
    segments: ["A", "B", "C"],
    qualifications: ["BSc", "MSc", "Diploma"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "42%",
    applied: "65%",
    calledBack: 123,
  },
  {
    title: "D2",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "D3",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],

    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "D4",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "D5",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "D6",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "D7",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
];

export const cardDataP = [
  {
    title: "P1",
    segments: ["A", "B", "C"],
    qualifications: ["BSc", "MSc", "Diploma"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "42%",
    applied: "65%",
    calledBack: 123,
  },
  {
    title: "P3",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],

    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "P4",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "P5",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "P6",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
  {
    title: "P7",
    segments: ["D", "E", "F"],
    qualifications: ["BCom", "MBA", "PhD"],
    cities: ["Chennai", "Bangalore", "Delhi"],
    overall: "51%",
    applied: "72%",
    calledBack: 98,
  },
];
